/*
 *  pendulum_cv.h
 *
 *  CVODE C prototype file for the functions defined in pendulum_cv.c
 *
 *  This file was generated by the program VFGEN, version: 2.5.0-dev
 *  Generated on 14-May-2014 at 21:03
 */

int pendulum_vf(realtype, N_Vector, N_Vector, void *);
int pendulum_jac(long int, realtype, N_Vector, N_Vector, DlsMat, void *,
                N_Vector, N_Vector, N_Vector);
int pendulum_func(realtype, N_Vector, realtype *, void *);
