/*
 *  pendulum_cv.c
 *
 *  CVODE C file for the vector field named: pendulum
 *
 *  This file was generated by the program VFGEN, version: 2.5.0-dev
 *  Generated on 14-May-2014 at 21:03
 */

#include <math.h>

/* Include headers for CVODE 2.7.0 */
#include <cvode/cvode.h>
#include <nvector/nvector_serial.h>
#include <cvode/cvode_dense.h>

/*
 *  The vector field.
 */

int pendulum_vf(realtype t, N_Vector y_, N_Vector f_, void *params)
{
    const realtype Pi = RCONST(M_PI);
    realtype theta, v;
    realtype g, b, L, m;
    realtype *p_;

    p_ = (realtype *) params;

    theta      = NV_Ith_S(y_,0);
    v          = NV_Ith_S(y_,1);

    g          = p_[0];
    b          = p_[1];
    L          = p_[2];
    m          = p_[3];

    NV_Ith_S(f_,0) = v;
    NV_Ith_S(f_,1) = -b/(L*L)*v/m-1.0/L*g*sin(theta);
    return 0;
}

/*
 *  The Jacobian.
 */

int pendulum_jac(long int N_, realtype t, N_Vector y_, N_Vector fy_, DlsMat jac_, void *params,
                N_Vector tmp1, N_Vector tmp2, N_Vector tmp3)
{
    const realtype Pi = RCONST(M_PI);
    realtype theta, v;
    realtype g, b, L, m;
    realtype *p_;

    p_ = (realtype *) params;

    theta      = NV_Ith_S(y_,0);
    v          = NV_Ith_S(y_,1);

    g          = p_[0];
    b          = p_[1];
    L          = p_[2];
    m          = p_[3];

    DENSE_ELEM(jac_, 0, 1) = 1.0;
    DENSE_ELEM(jac_, 1, 0) = -cos(theta)/L*g;
    DENSE_ELEM(jac_, 1, 1) = -b/(L*L)/m;
    return 0;
}

/*
 *  User-defined functions. 
 */

int pendulum_func(realtype t, N_Vector y_, realtype *func_, void *params)
{
    const realtype Pi = RCONST(M_PI);
    realtype theta, v;
    realtype g, b, L, m;
    realtype *p_;

    p_ = (realtype *) params;

    theta      = NV_Ith_S(y_,0);
    v          = NV_Ith_S(y_,1);

    g          = p_[0];
    b          = p_[1];
    L          = p_[2];
    m          = p_[3];

    /* energy:  */
    func_[0] =  (L*L)*(v*v)*m/2.0-cos(theta)*L*m*g;
    return 0;
}
