%
% sys_tau.m
%
% DDE-BIFTOOL MATLAB sys_tau function for: mg
%
% This file was generated by the program VFGEN, version: 2.5.0-dev
% Generated on 14-May-2014 at 21:03
%

function tau = sys_tau()

tau = [ 3 ];
return
