%
% sys_init.m
%
% DDEBIFTOOL MATLAB sys_init() function for: mg
%
% This file was generated by the program VFGEN, version: 2.5.0-dev
% Generated on 14-May-2014 at 21:03
%
%
function [name,dim] = sys_init()
    name = 'mg';
    dim = 1;
    path(path,'/home/wweckesser/ddebiftool');
    return;
