#
# MackeyGlass.R
#
# R vector field functions for: MackeyGlass
#
# This file was generated by the program VFGEN, version: 2.5.0-dev
# Generated on 14-May-2014 at 21:04
#


#
# MackeyGlass(t, state, parameters)
#
# The vector field function
#
MackeyGlass <- function(t, state, parameters) {
    x          <- state[1]
    a          <- parameters[1]
    b          <- parameters[2]
    tau        <- parameters[3]

    if (t < tau) {
        lag1 = 0.5-(0.02)*tau+(0.02)*t
    }
    else {
        lag1 = lagvalue(-tau+t, 1)
    }
    delayedx <- lag1;
    vf_ <- vector(len = 1)
    vf_[1] = -x*b+(1+delayedx^10)^(-1)*delayedx*a;
    return(list(vf_))
}

