#
# pendulumv.R
#
# R vector field functions for: pendulumv
#
# This file was generated by the program VFGEN, version: 2.5.0-dev
# Generated on 14-May-2014 at 21:04
#


#
# pendulumv(t, state, parameters)
#
# The vector field function
#
pendulumv <- function(t, state, parameters) {
    Pi <- pi
    theta      <- state[1]
    v          <- state[2]
    g          <- parameters[1]
    b          <- parameters[2]
    L          <- parameters[3]
    m          <- parameters[4]

    vf_ <- vector(len = 2)
    vf_[1] = v;
    vf_[2] = -sin(theta)*L^(-1)*g-L^(-2)*v*m^(-1)*b;
    return(list(vf_))
}

#
# pendulumv_jac(t, state, parameters)
#
# The jacobian function
#
pendulumv_jac <- function(t, state, parameters) {
    Pi <- pi;
    theta      <- state[1]
    v          <- state[2]
    g          <- parameters[1]
    b          <- parameters[2]
    L          <- parameters[3]
    m          <- parameters[4]
    jac_ = matrix(nrow = 2, ncol = 2)
    jac_[1,1] = 0
    jac_[1,2] = 1
    jac_[2,1] = -cos(theta)*L^(-1)*g
    jac_[2,2] = -L^(-2)*m^(-1)*b
    return(jac_)
}


#
# pendulumv_sol_energy
#
# This function implements the user-defined function "energy"
#
pendulumv_sol_energy <- function(sol, parameters) {
    Pi <- pi;
    t <- sol[, 1]
    theta      <- sol[, 2]
    v          <- sol[, 3]
    g          <- parameters[1]
    b          <- parameters[2]
    L          <- parameters[3]
    m          <- parameters[4]
    r_ <- 1/2*L^2*v^2*m-cos(theta)*L*m*g;
    return(r_)
}

#
# pendulumv_energy
#
# This function implements the user-defined function "energy"
#
pendulumv_energy <- function(t, state, parameters) {
    Pi <- pi;
    theta      <- state[1]
    v          <- state[2]
    g          <- parameters[1]
    b          <- parameters[2]
    L          <- parameters[3]
    m          <- parameters[4]
    r_ <- 1/2*L^2*v^2*m-cos(theta)*L*m*g;
    return(r_)
}

#
# pendulumv_sol_v
#
# This function implements the user-defined function "v"
#
pendulumv_sol_v <- function(sol, parameters) {
    Pi <- pi;
    t <- sol[, 1]
    theta      <- sol[, 2]
    v          <- sol[, 3]
    g          <- parameters[1]
    b          <- parameters[2]
    L          <- parameters[3]
    m          <- parameters[4]
    r_ <- v;
    return(r_)
}

#
# pendulumv_v
#
# This function implements the user-defined function "v"
#
pendulumv_v <- function(t, state, parameters) {
    Pi <- pi;
    theta      <- state[1]
    v          <- state[2]
    g          <- parameters[1]
    b          <- parameters[2]
    L          <- parameters[3]
    m          <- parameters[4]
    r_ <- v;
    return(r_)
}
