#
# vanderpol_dst.py
#
#
# This script uses PyDSTool to plot a solution to the
# differential equations defined in vanderpol.py
#
# This file was generated by the program VFGEN, version: 2.5.0-dev
# Generated on 14-May-2014 at 21:03
#

import sys
import matplotlib.pyplot as plt
import PyDSTool
import vanderpol

# Compute the solution
ds = vanderpol.args()
ode = PyDSTool.Generator.Vode_ODEsystem(ds)
traj = ode.compute('traj')
sol = traj.sample(dt=0.05)

# Plot the solution
lw = 1.5
plt.plot(sol['t'], sol['x'], linewidth=lw)
plt.plot(sol['t'], sol['y'], linewidth=lw)
plt.xlabel('t')
plt.title('vanderpol')
plt.legend(('x', 'y'))
plt.grid(True)

if len(sys.argv) > 1:
    plt.savefig(sys.argv[1], dpi=72)
else:
    plt.show()
