%
% MackeyGlass_dde23.m
%
% MATLAB vector field function for: MackeyGlass
%
% This file was generated by the program VFGEN, version: 2.5.0-dev
% Generated on 14-May-2014 at 21:03
%
%
% The lags are: {tau}
%
function vf_ = MackeyGlass_dde23(t,x_,Zlags_,p_)
    % State variables
    x          = x_(1);
    % Parameters
    a          = p_(1);
    b          = p_(2);
    tau        = p_(3);

    delayedx = Zlags_(1,1);
    vf_ = zeros(1,1);
    vf_(1) = -x*b+(1+delayedx^10)^(-1)*a*delayedx;

