%
% SIRdelay_dde23.m
%
% MATLAB vector field function for: SIRdelay
%
% This file was generated by the program VFGEN, version: 2.5.0-dev
% Generated on 14-May-2014 at 21:03
%
%
% The lags are: {tau}
%
function vf_ = SIRdelay_dde23(t,x_,Zlags_,p_)
    % State variables
    S          = x_(1);
    In         = x_(2);
    R          = x_(3);
    % Parameters
    alpha      = p_(1);
    tau        = p_(2);

    delayedS = Zlags_(1,1);
    delayedIn = Zlags_(2,1);
    vf_ = zeros(3,1);
    vf_(1) = -S*alpha*In;
    vf_(2) = alpha*(S*In-delayedS*delayedIn);
    vf_(3) = delayedS*alpha*delayedIn;

