c
c vanderpol_rhs.f
c
c Vector field functions for the vector field 'vanderpol'
c These functions are to be used with the Fortran ODE solver LSODA.
c
c This file was generated by the program VFGEN, version: 2.5.0-dev
c Generated on 14-May-2014 at 21:03
c
      subroutine vanderpol_rhs(n_,t_,y_,f_)
      implicit none
      integer n_
      double precision t_, y_, f_
      dimension y_(3), f_(2)
      double precision epsilon
      double precision x, y

c     --- Parameters ---
      epsilon    = y_(3)
c     --- State variables ---
      x          = y_(1)
      y          = y_(2)
c     --- The vector field ---
      f_(1) = 1.0D0/epsilon*( y+-3.3333333333333331D-01*x**(3.0D0)+x)
      f_(2) = -x

      return
      end

c
c Jacobian of the vector field 'vanderpol'
c
c The subroutine assumes that the full Jacobian is to be computed.
c ml_ and mu_ are ignored, and nrowpd_ is assumed to be n_.
c
      subroutine vanderpol_jac(n_,t_,y_,ml_,mu_,jac_,nrowpd_)
      implicit none
      integer n_, ml_, mu_, nrowpd_
      double precision t_, y_, jac_
      dimension y_(3), jac_(nrowpd_,2)
      double precision epsilon
      double precision x, y

c     --- Parameters ---
      epsilon    = y_(3)
c     --- State variables ---
      x          = y_(1)
      y          = y_(2)
c     --- Jacobian ---
      jac_(1, 1) = 1.0D0/epsilon*(-x**(2.0D0)+1.0D0)
      jac_(1, 2) = epsilon**(-1.0D0)
      jac_(2, 1) = -1.0D0
c     jac_(2, 2) = 0

      return
      end

