/*
 *  pendulum_gvf.h
 *
 *  GSL C prototype file for the functions defined in pendulum_gvf.c
 *
 *  This file was generated by the program VFGEN, version: 2.5.0-dev
 *  Generated on 14-May-2014 at 21:03
 */

int pendulum_vf(double, const double [], double [], void *);
int pendulum_jac(double, const double [], double *, double *, void *);
int pendulum_jacp(double, const double [], double *, void *);
double pendulum_energy(double, const double [], void *);
