/*
 *  pendulum_gvf.c
 *
 *  GSL C file for the vector field named: pendulum
 *
 *  This file was generated by the program VFGEN, version: 2.5.0-dev
 *  Generated on 14-May-2014 at 21:03
 */

#include <math.h>
#include <gsl/gsl_errno.h>
#include <gsl/gsl_matrix.h>
#include <gsl/gsl_odeiv.h>

/*
 *  The vector field.
 */

int pendulum_vf(double t, const double y_[], double f_[], void *params)
{
    const double Pi = M_PI;
    double theta, v;
    double g, b, L, m;
    double *p_;

    p_ = (double *) params;

    theta      = y_[0];
    v          = y_[1];

    g          = p_[0];
    b          = p_[1];
    L          = p_[2];
    m          = p_[3];

    f_[0] = v;
    f_[1] = -v/m*b/(L*L)-g*sin(theta)/L;

    return GSL_SUCCESS;
}

/*
 *  The Jacobian.
 */

int pendulum_jac(double t, const double y_[], double *jac_, double *dfdt_, void *params)
{
    const double Pi = M_PI;
    double theta, v;
    double g, b, L, m;
    double *p_;

    p_ = (double *) params;

    theta      = y_[0];
    v          = y_[1];

    g          = p_[0];
    b          = p_[1];
    L          = p_[2];
    m          = p_[3];

    gsl_matrix_view dfdy_mat = gsl_matrix_view_array(jac_,2,2);
    gsl_matrix *m_ = &dfdy_mat.matrix;

    gsl_matrix_set(m_, 0, 0, 0.0);
    gsl_matrix_set(m_, 0, 1, 1.0);
    gsl_matrix_set(m_, 1, 0, -g*cos(theta)/L);
    gsl_matrix_set(m_, 1, 1, -1.0/m*b/(L*L));

    dfdt_[0] = 0.0;
    dfdt_[1] = 0.0;

    return GSL_SUCCESS;
}

/*
 *  The Jacobian with respect to the parameters.
 */

int pendulum_jacp(double t, const double y_[], double *jacp_, void *params)
{
    const double Pi = M_PI;
    double theta, v;
    double g, b, L, m;
    double *p_;

    p_ = (double *) params;

    theta      = y_[0];
    v          = y_[1];

    g          = p_[0];
    b          = p_[1];
    L          = p_[2];
    m          = p_[3];

    gsl_matrix_view dfdp_mat = gsl_matrix_view_array(jacp_,2,4);
    gsl_matrix *m_ = &dfdp_mat.matrix;

    gsl_matrix_set(m_, 0, 0, 0.0);
    gsl_matrix_set(m_, 0, 1, 0.0);
    gsl_matrix_set(m_, 0, 2, 0.0);
    gsl_matrix_set(m_, 0, 3, 0.0);
    gsl_matrix_set(m_, 1, 0, -sin(theta)/L);
    gsl_matrix_set(m_, 1, 1, -v/m/(L*L));
    gsl_matrix_set(m_, 1, 2,  2.0*v/m*b/(L*L*L)+g*sin(theta)/(L*L));
    gsl_matrix_set(m_, 1, 3, v/(m*m)*b/(L*L));

    return GSL_SUCCESS;
}

/*
 *  User function: energy
 */

double pendulum_energy(double t, const double y_[], void *params)
{
    const double Pi = M_PI;
    double theta, v;
    double g, b, L, m;
    double *p_;

    p_ = (double *) params;

    theta      = y_[0];
    v          = y_[1];

    g          = p_[0];
    b          = p_[1];
    L          = p_[2];
    m          = p_[3];

    return -m*g*cos(theta)*L+(v*v)*m*(L*L)/2.0;
}
