//
//  pendulum_adolc.h
//
//  ADOLC C++ header file for the functions defined in pendulum_adolc.cpp
//
//  This file was generated by the program VFGEN, version: 2.5.0-dev
//  Generated on 14-May-2014 at 21:03
//

void pendulum_vf(short int, double *, double *, double *);
