c
c vanderpol_dr5.f
c
c Fortran 77 program that uses RADAU5 to solve the differential equations
c defined in the vector field 'vanderpol'
c
c This file was generated by the program VFGEN, version: 2.5.0-dev
c Generated on 14-May-2014 at 21:04
c
      program vanderpol
      implicit none
      integer nd_, lwork_, liwork_
      parameter (nd_=2, lwork_=60, liwork_=26)
      double precision y_, rpar_, work_, iwork_
      dimension y_(nd_), work_(lwork_), iwork_(liwork_)
      integer n_, ipar_, ijac_, mljac_, mujac_, imas_, mlmas_, mumas_
      integer iout_, itol_, idid_
      dimension rpar_(1)
      integer i_
      double precision t_, tstop_
      double precision atol_, rtol_, h_
      double precision epsilon
      double precision x, y
      external vanderpol_rhs
      external vanderpol_jac
      external vanderpol_out

      n_ = 2
      ijac_ = 1
      mljac_ = n_
      imas_ = 0
      iout_ = 1
c     --- t range ---
      t_ = 0.0D0
      tstop_  = 10.0D0
c     --- Parameters ---
      epsilon = 2.0000000000000001D-01
      rpar_(1) = epsilon
c     --- Initial conditions ---
      x = 1.0000000000000000D-02
      y = 0.0D0
      y_(1) = x
      y_(2) = y
c     --- Solver tolerances ---
      rtol_ = 1.0D-6
      atol_ = 1.0D-8
      itol_ = 0
c     --- Initial step size ---
      h_ = 1.0D-5
c     --- Set default values ---
      do i_ = 1, 20
          iwork_(i_) = 0
          work_(i_) = 0.0D0
      end do
c     --- Call RADAU5 ---
      call radau5(n_,vanderpol_rhs, t_, y_, tstop_, h_,
     &           rtol_, atol_, itol_,
     &           vanderpol_jac, ijac_, mljac_, mujac_,
     &           vanderpol_rhs, imas_, mlmas_, mumas_,
     &           vanderpol_out, iout_,
     &           work_, lwork_, iwork_, liwork_, rpar_, ipar_, idid_)
      stop
      end

