/*
 *  pendulum_taylor7.h
 *
 *  C prototype file for the functions defined in pendulum_taylor7.c
 *
 *  This file was generated by the program VFGEN, version: 2.5.0-dev
 *  Generated on 14-May-2014 at 21:04
 */

void pendulum_vf(double, const double [], double [], double []);
void pendulum_diff1(double deriv[], double x_[], double p_[],double v1_[]);
void pendulum_diff2(double deriv[], double x_[], double p_[],double v1_[],double v2_[]);
void pendulum_diff3(double deriv[], double x_[], double p_[],double v1_[],double v2_[],double v3_[]);
void pendulum_diff4(double deriv[], double x_[], double p_[],double v1_[],double v2_[],double v3_[],double v4_[]);
void pendulum_diff5(double deriv[], double x_[], double p_[],double v1_[],double v2_[],double v3_[],double v4_[],double v5_[]);
void pendulum_diff6(double deriv[], double x_[], double p_[],double v1_[],double v2_[],double v3_[],double v4_[],double v5_[],double v6_[]);
void pendulum_derivs7(double Xderiv[7][2], double X[], double params[]);
void pendulum_evaltaylor7(double Xnew[], double h, double X[], double Xderiv[7][2]);
