#
# vanderpol.m
#
# Octave vector field functions for: vanderpol
#
# This file was generated by the program VFGEN, version: 2.5.0-dev
# Generated on 14-May-2014 at 21:03
#

# The next line, containing just the number 1, is not a mistake!
# It allows the file to define more than one function.
1;

#
# vanderpol_vf
#
# The vector field 
#
function vf_ = vanderpol_vf(x_, t)
    global vanderpol_parameters;
    x          = x_(1);
    y          = x_(2);
    epsilon    = vanderpol_parameters(1);
    vf_ = zeros(2, 1);
    vf_(1) = (-(0.33333333333333333334)*x^3+x+y)*epsilon^(-1);
    vf_(2) = -x;
endfunction

#
# vanderpol_jac
#
# The Jacobian of the vector field
#
function jac_ = vanderpol_jac(x_, t)
    global vanderpol_parameters;
    x          = x_(1);
    y          = x_(2);
    epsilon    = vanderpol_parameters(1);
    jac_ = zeros(2, 2);
    jac_(1, 1) = (1-x^2)*epsilon^(-1);
    jac_(1, 2) = epsilon^(-1);
    jac_(2, 1) = -1;
endfunction

