%
% pendulum_hess.m
%
% This MATLAB function computes the Hessians of the vector field
% defined in pendulum_vf.m.
%
% hess_(n,i,j) is the second partial derivative of the n-th component
% of the vector field, taken with respect to the i-th and j-th variables.
%
% This file was generated by the program VFGEN, version: 2.5.0-dev
% Generated on 14-May-2014 at 21:03
%
%
function hess_ = pendulum_hess(t,x_,p_)
    Pi = pi;
    theta      = x_(1);
    v          = x_(2);
    g          = p_(1);
    b          = p_(2);
    L          = p_(3);
    m          = p_(4);

    hess_ = zeros(2,2,2);


    hess_(2,1,1) = sin(theta)*L^(-1)*g;

