%
% pendulum_jacp.m
%
% This MATLAB function computes the Jacobian with respect to the parameters
% of the vector field defined in pendulum_vf.m.
%
% This file was generated by the program VFGEN, version: 2.5.0-dev
% Generated on 14-May-2014 at 21:03
%
%
function jacp_ = pendulum_jacp(t,x_,p_)
    Pi = pi;
    theta      = x_(1);
    v          = x_(2);
    g          = p_(1);
    b          = p_(2);
    L          = p_(3);
    m          = p_(4);
    jacp_ = zeros(2,4);
    jacp_(2,1) = -sin(theta)*L^(-1);
    jacp_(2,2) = -L^(-2)*v*m^(-1);
    jacp_(2,3) = sin(theta)*L^(-2)*g+2*b*L^(-3)*v*m^(-1);
    jacp_(2,4) = b*L^(-2)*v*m^(-2);

