%
% pendulum_der3.m
%
% This MATLAB function computes the third derivatives of the vector field
% defined in pendulum_vf.m.
%
% der3_(n,i,j,k) is the third partial derivative of the n-th component
% of the vector field, taken with respect to the i-th, j-th and k-th variables.
%
% This file was generated by the program VFGEN, version: 2.5.0-dev
% Generated on 14-May-2014 at 21:03
%
%
function der3_ = pendulum_der3(t,x_,p_)
    Pi = pi;
    theta      = x_(1);
    v          = x_(2);
    g          = p_(1);
    b          = p_(2);
    L          = p_(3);
    m          = p_(4);

    der3_ = zeros(2,2,2,2);


    der3_(2,1,1,1) = cos(theta)*L^(-1)*g;

