%
% pendulum_vf.m
%
% MATLAB vector field function for: pendulum
%
% This file was generated by the program VFGEN, version: 2.5.0-dev
% Generated on 14-May-2014 at 21:03
%
%
function vf_ = pendulum_vf(t,x_,p_)
    Pi = pi;
    theta      = x_(1);
    v          = x_(2);
    g          = p_(1);
    b          = p_(2);
    L          = p_(3);
    m          = p_(4);
    vf_ = zeros(2,1);
    vf_(1) = v;
    vf_(2) = -b*L^(-2)*v*m^(-1)-sin(theta)*L^(-1)*g;

