%
% pendulum_hessp.m
%
% This MATLAB function computes the derivatives of the vector field
% defined in pendulum_vf.m.
%
% hessp_(n,i,j) is the second partial derivative of the n-th component
% of the vector field, taken with respect to the i-th variable
% and the j-th parameter.
%
% This file was generated by the program VFGEN, version: 2.5.0-dev
% Generated on 14-May-2014 at 21:03
%
%
function hessp_ = pendulum_hessp(t,x_,p_)
    Pi = pi;
    theta      = x_(1);
    v          = x_(2);
    g          = p_(1);
    b          = p_(2);
    L          = p_(3);
    m          = p_(4);

    hessp_ = zeros(2,2,4);


    hessp_(2,1,1) = -cos(theta)*L^(-1);
    hessp_(2,1,3) = cos(theta)*L^(-2)*g;
    hessp_(2,2,2) = -L^(-2)*m^(-1);
    hessp_(2,2,3) = 2*b*L^(-3)*m^(-1);
    hessp_(2,2,4) = b*L^(-2)*m^(-2);

